apiVersion: v1
kind: Service
metadata:
  name: i3-gateway
spec:
  selector:
    app: i3-gateway
  ports:
  - protocol: TCP
    port: 9084
    nodePort: 30024
    targetPort: 9084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i3-gateway
spec:
  selector:
      matchLabels:
        app: i3-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: i3-gateway
    spec:
      containers:
        - name: i3-gateway
          image: awsramana/i3-gateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 9084