apiVersion: v1
kind: Service
metadata:
  name: i3-dbservice
spec:
  selector:
    app: i3-dbservice
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30030
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i3-dbservice
spec:
  selector:
      matchLabels:
        app: i3-dbservice
  replicas: 1
  template:
    metadata:
      labels:
        app: i3-dbservice
    spec:
      containers:
        - name: i3-dbservice
          image: awsramana/i3-db-services:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8080
