apiVersion: v1
kind: Service
metadata:
  name: i3-discover
spec:
  selector:
    app: i3-discover
  ports:
  - protocol: TCP
    port: 11000
    nodePort: 30020
    targetPort: 11000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i3-discover
spec:
  selector:
      matchLabels:
        app: i3-discover
  replicas: 1
  template:
    metadata:
      labels:
        app: i3-discover
    spec:
      containers:
        - name: i3-discover
          image: awsramana/i3-discover:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 11000